#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ref
Version  : 2.0.0
Release  : 7
URL      : https://rubygems.org/downloads/ref-2.0.0.gem
Source0  : https://rubygems.org/downloads/ref-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# Ref
[![Gem Version](https://badge.fury.io/rb/ref.svg)](http://badge.fury.io/rb/ref) [![Build Status](https://travis-ci.org/ruby-concurrency/ref.svg?branch=master)](https://travis-ci.org/ruby-concurrency/ref) [![Coverage Status](https://img.shields.io/coveralls/ruby-concurrency/ref/master.svg)](https://coveralls.io/r/ruby-concurrency/ref) [![Code Climate](https://codeclimate.com/github/ruby-concurrency/ref.svg)](https://codeclimate.com/github/ruby-concurrency/ref) [![Dependency Status](https://gemnasium.com/ruby-concurrency/ref.svg)](https://gemnasium.com/ruby-concurrency/ref) [![License](https://img.shields.io/badge/license-MIT-green.svg)](http://opensource.org/licenses/MIT) [![Gitter chat](http://img.shields.io/badge/gitter-join%20chat%20%E2%86%92-brightgreen.svg)](https://gitter.im/ruby-concurrency/concurrent-ruby)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ref-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-ref.gemspec

%build
gem build rubygem-ref.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ref-2.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/ref-2.0.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/cdesc-AbstractReferenceKeyMap.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/put-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/ref_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/remove_reference_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceKeyMap/to_h-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/cdesc-AbstractReferenceValueMap.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/put-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/remove_reference_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/to_h-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/AbstractReferenceValueMap/values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/ObjectSpace/cdesc-ObjectSpace.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/Reference/cdesc-Reference.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/Reference/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/Reference/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/Reference/object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/Reference/referenced_object_id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/ReferenceQueue/cdesc-ReferenceQueue.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/ReferenceQueue/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/ReferenceQueue/monitor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/ReferenceQueue/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/ReferenceQueue/pop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/ReferenceQueue/push-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/ReferenceQueue/shift-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/ReferenceQueue/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/SoftKeyMap/cdesc-SoftKeyMap.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/SoftReference/cdesc-SoftReference.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/SoftReference/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/SoftReference/object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/SoftValueMap/cdesc-SoftValueMap.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/StrongReference/cdesc-StrongReference.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/StrongReference/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/StrongReference/object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakKeyMap/cdesc-WeakKeyMap.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakReference/ReferencePointer/cdesc-ReferencePointer.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakReference/ReferencePointer/cleanup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakReference/ReferencePointer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakReference/ReferencePointer/object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakReference/ReferencePointer/supports_backreference%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakReference/cdesc-WeakReference.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakReference/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakReference/object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/WeakValueMap/cdesc-WeakValueMap.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/cdesc-Ref.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/Ref/jruby%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/ref-2.0.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/MIT_LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/ext/java/org/jruby/ext/ref/ReferencesService.java
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/ext/java/org/jruby/ext/ref/RubySoftReference.java
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/ext/java/org/jruby/ext/ref/RubyWeakReference.java
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/abstract_reference_key_map.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/abstract_reference_value_map.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/reference.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/reference_queue.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/soft_key_map.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/soft_reference.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/soft_value_map.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/strong_reference.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/weak_key_map.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/weak_reference.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/weak_reference/pure_ruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/weak_reference/weak_ref.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref/weak_value_map.rb
/usr/lib64/ruby/gems/2.2.0/gems/ref-2.0.0/lib/ref_ext.jar
/usr/lib64/ruby/gems/2.2.0/specifications/ref-2.0.0.gemspec
