#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ref
Version  : 2.0.0
Release  : 9
URL      : https://rubygems.org/downloads/ref-2.0.0.gem
Source0  : https://rubygems.org/downloads/ref-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# Ref
[![Gem Version](https://badge.fury.io/rb/ref.svg)](http://badge.fury.io/rb/ref) [![Build Status](https://travis-ci.org/ruby-concurrency/ref.svg?branch=master)](https://travis-ci.org/ruby-concurrency/ref) [![Coverage Status](https://img.shields.io/coveralls/ruby-concurrency/ref/master.svg)](https://coveralls.io/r/ruby-concurrency/ref) [![Code Climate](https://codeclimate.com/github/ruby-concurrency/ref.svg)](https://codeclimate.com/github/ruby-concurrency/ref) [![Dependency Status](https://gemnasium.com/ruby-concurrency/ref.svg)](https://gemnasium.com/ruby-concurrency/ref) [![License](https://img.shields.io/badge/license-MIT-green.svg)](http://opensource.org/licenses/MIT) [![Gitter chat](http://img.shields.io/badge/gitter-join%20chat%20%E2%86%92-brightgreen.svg)](https://gitter.im/ruby-concurrency/concurrent-ruby)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ref-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-ref.gemspec

%build
gem build rubygem-ref.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ref-2.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ref-2.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/MIT_LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/ext/java/org/jruby/ext/ref/ReferencesService.java
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/ext/java/org/jruby/ext/ref/RubySoftReference.java
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/ext/java/org/jruby/ext/ref/RubyWeakReference.java
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/abstract_reference_key_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/abstract_reference_value_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/reference.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/reference_queue.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/soft_key_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/soft_reference.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/soft_value_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/strong_reference.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/weak_key_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/weak_reference.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/weak_reference/pure_ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/weak_reference/weak_ref.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref/weak_value_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/ref-2.0.0/lib/ref_ext.jar
/usr/lib64/ruby/gems/2.3.0/specifications/ref-2.0.0.gemspec
